In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense


In [13]:
text = "This is VIT"
chars = sorted(list(set(text)))
print(text)
print(chars)
char_to_index = {char: i for i, char in enumerate(chars)}
index_to_char = {i: char for i, char in enumerate(chars)}
print(char_to_index)
print(index_to_char)

This is VIT
[' ', 'I', 'T', 'V', 'h', 'i', 's']
{' ': 0, 'I': 1, 'T': 2, 'V': 3, 'h': 4, 'i': 5, 's': 6}
{0: ' ', 1: 'I', 2: 'T', 3: 'V', 4: 'h', 5: 'i', 6: 's'}


In [15]:
seq_length = 3
sequences = []
labels = []

for i in range(len(text) - seq_length):
	seq = text[i:i+seq_length]
	label = text[i+seq_length]
	sequences.append([char_to_index[char] for char in seq])
	labels.append(char_to_index[label])
print(sequences)
print(labels)

[[2, 4, 5], [4, 5, 6], [5, 6, 0], [6, 0, 5], [0, 5, 6], [5, 6, 0], [6, 0, 3], [0, 3, 1]]
[6, 0, 5, 6, 0, 3, 1, 2]


In [ ]:
X = np.array(sequences)
y = np.array(labels)

X_one_hot = tf.one_hot(X, len(chars))
y_one_hot = tf.one_hot(y, len(chars))

In [6]:
X_one_hot

<tf.Tensor: shape=(8, 3, 7), dtype=float32, numpy=
array([[[0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.]],

       [[0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.]],

       [[1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]],

       [[0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.]],

       [[1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [7]:
y_one_hot

<tf.Tensor: shape=(8, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>

In [16]:
model = Sequential()
model.add(SimpleRNN(50, input_shape=(seq_length, len(chars)), activation='relu'))
model.add(Dense(len(chars), activation='softmax'))


In [17]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [18]:
model.fit(X_one_hot, y_one_hot, epochs=100)


Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 1.9169 - accuracy: 0.3750
Epoch 2/100
1/1 [==============================] - 0s 13ms/step - loss: 1.8916 - accuracy: 0.3750
Epoch 3/100
1/1 [==============================] - 0s 20ms/step - loss: 1.8667 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 12ms/step - loss: 1.8423 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 19ms/step - loss: 1.8184 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 11ms/step - loss: 1.7950 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 14ms/step - loss: 1.7724 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 13ms/step - loss: 1.7499 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 14ms/step - loss: 1.7276 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 13ms/step - loss: 1.7053 - accuracy: 0.5000
Epoch 11/100
1/1 [===

In [31]:
start_seq = "This"
generated_text = start_seq

for i in range(2):
	x = np.array([[char_to_index[char] for char in generated_text[-seq_length:]]])
	x_one_hot = tf.one_hot(x, len(chars))
	prediction = model.predict(x_one_hot)
	next_index = np.argmax(prediction)
	next_char = index_to_char[next_index]
	generated_text += next_char

print("Generated Text:")
print(generated_text)


1/1 [==============================] - 0s 27ms/step
Generated Text:
This i
